/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CrategoryWhereInput } from "./CrategoryWhereInput";
import { Type } from "class-transformer";
import { CrategoryOrderByInput } from "./CrategoryOrderByInput";

@ArgsType()
class CrategoryFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => CrategoryWhereInput,
  })
  @Field(() => CrategoryWhereInput, { nullable: true })
  @Type(() => CrategoryWhereInput)
  where?: CrategoryWhereInput;

  @ApiProperty({
    required: false,
    type: CrategoryOrderByInput,
  })
  @Field(() => CrategoryOrderByInput, { nullable: true })
  @Type(() => CrategoryOrderByInput)
  orderBy?: CrategoryOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { CrategoryFindManyArgs };
